
#
# This makefile was generated with the following command:
# /home/bouchra/Downloads/omnetpp-5.4.1/bin/opp_runall -j4 ./CloneAttackDetectionInSaaS -u Cmdenv -c MTLSD -r 1
#

SIMULATIONCMD = ./CloneAttackDetectionInSaaS -u Cmdenv -c MTLSD -s --cmdenv-redirect-output=true
TARGETS =  run1

.PHONY: $(TARGETS)

all: $(TARGETS)
	@echo All runs completed.

run1:
	$(SIMULATIONCMD) -r 1


